version: "3"

services:

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    container_name: web
    volumes:
      - ./client/src:/usr/src/app
    command: 'yarn dev'
    ports:
      - "3000:3000"
    depends_on:
      - server
      - db

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: server
    command: 'nest start'
    volumes:
     - ./server/nest:/usr/src/app
    ports:
      - "3018:3018"
    depends_on:
      - db
      
  db:
    platform: linux/x86_64
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: KAICHOKU_CONNECT
      MYSQL_ROOT_PASSWORD: $ROOT_PASSWORD
    ports:
      - 3306:3306
    volumes:
      - ./data/mysql:/var/lib/mysql
      - ./conf:/etc/mysql/conf.d
    command: --default-authentication-plugin=mysql_native_password